2023-10-29 09:03:29,777 INFO: Microblog startup [in C:\Users\Kourosh\PycharmProjects\mymicroblog\app\__init__.py:47]
2023-10-29 09:03:30,415 INFO: Microblog startup [in C:\Users\Kourosh\PycharmProjects\mymicroblog\app\__init__.py:47]
2023-10-29 09:06:22,822 INFO: Microblog startup [in C:\Users\Kourosh\PycharmProjects\mymicroblog\app\__init__.py:47]
2023-10-29 09:06:31,395 ERROR: Exception on /edit_profile [POST] [in C:\Users\Kourosh\PycharmProjects\mymicroblog\venv\Lib\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "C:\Users\Kourosh\PycharmProjects\mymicroblog\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1969, in _exec_single_context
    self.dialect.do_execute(
  File "C:\Users\Kourosh\PycharmProjects\mymicroblog\venv\Lib\site-packages\sqlalchemy\engine\default.py", line 922, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: user.username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Kourosh\PycharmProjects\mymicroblog\venv\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kourosh\PycharmProjects\mymicroblog\venv\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kourosh\PycharmProjects\mymicroblog\venv\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kourosh\PycharmProjects\mymicroblog\venv\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kourosh\PycharmProjects\mymicroblog\venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kourosh\PycharmProjects\mymicroblog\app\routes.py", line 95, in edit_profile
    db.session.commit()
  File "C:\Users\Kourosh\PycharmProjects\mymicroblog\venv\Lib\site-packages\sqlalchemy\orm\scoping.py", line 597, in commit
    return self._proxied.commit()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kourosh\PycharmProjects\mymicroblog\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 1967, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "C:\Users\Kourosh\PycharmProjects\mymicroblog\venv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kourosh\PycharmProjects\mymicroblog\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 1256, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "C:\Users\Kourosh\PycharmProjects\mymicroblog\venv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kourosh\PycharmProjects\mymicroblog\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 1231, in _prepare_impl
    self.session.flush()
  File "C:\Users\Kourosh\PycharmProjects\mymicroblog\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 4310, in flush
    self._flush(objects)
  File "C:\Users\Kourosh\PycharmProjects\mymicroblog\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 4445, in _flush
    with util.safe_reraise():
  File "C:\Users\Kourosh\PycharmProjects\mymicroblog\venv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\Kourosh\PycharmProjects\mymicroblog\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 4406, in _flush
    flush_context.execute()
  File "C:\Users\Kourosh\PycharmProjects\mymicroblog\venv\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 466, in execute
    rec.execute(self)
  File "C:\Users\Kourosh\PycharmProjects\mymicroblog\venv\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "C:\Users\Kourosh\PycharmProjects\mymicroblog\venv\Lib\site-packages\sqlalchemy\orm\persistence.py", line 85, in save_obj
    _emit_update_statements(
  File "C:\Users\Kourosh\PycharmProjects\mymicroblog\venv\Lib\site-packages\sqlalchemy\orm\persistence.py", line 909, in _emit_update_statements
    c = connection.execute(
        ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kourosh\PycharmProjects\mymicroblog\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1416, in execute
    return meth(
           ^^^^^
  File "C:\Users\Kourosh\PycharmProjects\mymicroblog\venv\Lib\site-packages\sqlalchemy\sql\elements.py", line 516, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kourosh\PycharmProjects\mymicroblog\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1639, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kourosh\PycharmProjects\mymicroblog\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1848, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kourosh\PycharmProjects\mymicroblog\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1988, in _exec_single_context
    self._handle_dbapi_exception(
  File "C:\Users\Kourosh\PycharmProjects\mymicroblog\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 2343, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\Users\Kourosh\PycharmProjects\mymicroblog\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1969, in _exec_single_context
    self.dialect.do_execute(
  File "C:\Users\Kourosh\PycharmProjects\mymicroblog\venv\Lib\site-packages\sqlalchemy\engine\default.py", line 922, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: user.username
[SQL: UPDATE user SET username=?, about_me=? WHERE user.id = ?]
[parameters: ('akbar', 'dfdoi diofgdio sdfklj', 3)]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2023-10-29 09:10:00,035 INFO: Microblog startup [in C:\Users\Kourosh\PycharmProjects\mymicroblog\app\__init__.py:47]
2023-10-29 09:10:04,457 ERROR: Exception on /edit_profile [GET] [in C:\Users\Kourosh\PycharmProjects\mymicroblog\venv\Lib\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "C:\Users\Kourosh\PycharmProjects\mymicroblog\venv\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kourosh\PycharmProjects\mymicroblog\venv\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kourosh\PycharmProjects\mymicroblog\venv\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kourosh\PycharmProjects\mymicroblog\venv\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kourosh\PycharmProjects\mymicroblog\venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kourosh\PycharmProjects\mymicroblog\app\routes.py", line 91, in edit_profile
    form = EditProfileForm()
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\Kourosh\PycharmProjects\mymicroblog\venv\Lib\site-packages\wtforms\form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: EditProfileForm.__init__() missing 1 required positional argument: 'original_username'
2023-10-29 09:11:38,808 INFO: Microblog startup [in C:\Users\Kourosh\PycharmProjects\mymicroblog\app\__init__.py:47]
