2023-11-04 11:57:14,543 ERROR: Unhandled exception [in /home/kourosh/PycharmProjects/mymicroblog/./app/tasks.py:49]
Traceback (most recent call last):
  File "/home/kourosh/PycharmProjects/mymicroblog/./app/tasks.py", line 41, in export_posts
    send_email('[Microblog] Your blog posts',
  File "/home/kourosh/PycharmProjects/mymicroblog/./app/email.py", line 21, in send_email
    mail.send(msg)
  File "/home/kourosh/PycharmProjects/mymicroblog/venv/lib/python3.10/site-packages/flask_mail.py", line 491, in send
    with self.connect() as connection:
  File "/home/kourosh/PycharmProjects/mymicroblog/venv/lib/python3.10/site-packages/flask_mail.py", line 144, in __enter__
    self.host = self.configure_host()
  File "/home/kourosh/PycharmProjects/mymicroblog/venv/lib/python3.10/site-packages/flask_mail.py", line 158, in configure_host
    host = smtplib.SMTP(self.mail.server, self.mail.port)
  File "/usr/lib/python3.10/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python3.10/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python3.10/smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable
2023-11-04 11:57:20,068 INFO: Microblog startup [in /home/kourosh/PycharmProjects/mymicroblog/./app/__init__.py:88]
2023-11-04 11:57:46,377 ERROR: Unhandled exception [in /home/kourosh/PycharmProjects/mymicroblog/./app/tasks.py:49]
Traceback (most recent call last):
  File "/home/kourosh/PycharmProjects/mymicroblog/./app/tasks.py", line 41, in export_posts
    send_email('[Microblog] Your blog posts',
  File "/home/kourosh/PycharmProjects/mymicroblog/./app/email.py", line 21, in send_email
    mail.send(msg)
  File "/home/kourosh/PycharmProjects/mymicroblog/venv/lib/python3.10/site-packages/flask_mail.py", line 491, in send
    with self.connect() as connection:
  File "/home/kourosh/PycharmProjects/mymicroblog/venv/lib/python3.10/site-packages/flask_mail.py", line 144, in __enter__
    self.host = self.configure_host()
  File "/home/kourosh/PycharmProjects/mymicroblog/venv/lib/python3.10/site-packages/flask_mail.py", line 158, in configure_host
    host = smtplib.SMTP(self.mail.server, self.mail.port)
  File "/usr/lib/python3.10/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python3.10/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python3.10/smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable
2023-11-04 11:57:51,899 INFO: Microblog startup [in /home/kourosh/PycharmProjects/mymicroblog/./app/__init__.py:88]
2023-11-04 11:58:18,041 ERROR: Unhandled exception [in /home/kourosh/PycharmProjects/mymicroblog/./app/tasks.py:49]
Traceback (most recent call last):
  File "/home/kourosh/PycharmProjects/mymicroblog/./app/tasks.py", line 41, in export_posts
    send_email('[Microblog] Your blog posts',
  File "/home/kourosh/PycharmProjects/mymicroblog/./app/email.py", line 21, in send_email
    mail.send(msg)
  File "/home/kourosh/PycharmProjects/mymicroblog/venv/lib/python3.10/site-packages/flask_mail.py", line 491, in send
    with self.connect() as connection:
  File "/home/kourosh/PycharmProjects/mymicroblog/venv/lib/python3.10/site-packages/flask_mail.py", line 144, in __enter__
    self.host = self.configure_host()
  File "/home/kourosh/PycharmProjects/mymicroblog/venv/lib/python3.10/site-packages/flask_mail.py", line 158, in configure_host
    host = smtplib.SMTP(self.mail.server, self.mail.port)
  File "/usr/lib/python3.10/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python3.10/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python3.10/smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable
2023-11-04 11:58:43,140 INFO: Microblog startup [in /home/kourosh/PycharmProjects/mymicroblog/app/__init__.py:88]
2023-11-04 11:58:48,988 INFO: Microblog startup [in /home/kourosh/PycharmProjects/mymicroblog/app/__init__.py:88]
2023-11-04 11:58:49,647 INFO: Microblog startup [in /home/kourosh/PycharmProjects/mymicroblog/app/__init__.py:88]
2023-11-04 11:58:59,018 INFO: Microblog startup [in /home/kourosh/PycharmProjects/mymicroblog/./app/__init__.py:88]
2023-11-04 11:59:25,171 ERROR: Unhandled exception [in /home/kourosh/PycharmProjects/mymicroblog/./app/tasks.py:51]
Traceback (most recent call last):
  File "/home/kourosh/PycharmProjects/mymicroblog/./app/tasks.py", line 41, in export_posts
    send_email('[Microblog] Your blog posts',
  File "/home/kourosh/PycharmProjects/mymicroblog/./app/email.py", line 21, in send_email
    mail.send(msg)
  File "/home/kourosh/PycharmProjects/mymicroblog/venv/lib/python3.10/site-packages/flask_mail.py", line 491, in send
    with self.connect() as connection:
  File "/home/kourosh/PycharmProjects/mymicroblog/venv/lib/python3.10/site-packages/flask_mail.py", line 144, in __enter__
    self.host = self.configure_host()
  File "/home/kourosh/PycharmProjects/mymicroblog/venv/lib/python3.10/site-packages/flask_mail.py", line 158, in configure_host
    host = smtplib.SMTP(self.mail.server, self.mail.port)
  File "/usr/lib/python3.10/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python3.10/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python3.10/smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable
2023-11-04 11:59:30,699 INFO: Microblog startup [in /home/kourosh/PycharmProjects/mymicroblog/./app/__init__.py:88]
2023-11-04 11:59:56,875 ERROR: Unhandled exception [in /home/kourosh/PycharmProjects/mymicroblog/./app/tasks.py:51]
Traceback (most recent call last):
  File "/home/kourosh/PycharmProjects/mymicroblog/./app/tasks.py", line 41, in export_posts
    send_email('[Microblog] Your blog posts',
  File "/home/kourosh/PycharmProjects/mymicroblog/./app/email.py", line 21, in send_email
    mail.send(msg)
  File "/home/kourosh/PycharmProjects/mymicroblog/venv/lib/python3.10/site-packages/flask_mail.py", line 491, in send
    with self.connect() as connection:
  File "/home/kourosh/PycharmProjects/mymicroblog/venv/lib/python3.10/site-packages/flask_mail.py", line 144, in __enter__
    self.host = self.configure_host()
  File "/home/kourosh/PycharmProjects/mymicroblog/venv/lib/python3.10/site-packages/flask_mail.py", line 158, in configure_host
    host = smtplib.SMTP(self.mail.server, self.mail.port)
  File "/usr/lib/python3.10/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python3.10/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python3.10/smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable
2023-11-04 12:01:31,017 INFO: Microblog startup [in /home/kourosh/PycharmProjects/mymicroblog/app/__init__.py:88]
2023-11-04 12:01:31,650 INFO: Microblog startup [in /home/kourosh/PycharmProjects/mymicroblog/app/__init__.py:88]
2023-11-04 12:01:37,188 INFO: Microblog startup [in /home/kourosh/PycharmProjects/mymicroblog/./app/__init__.py:88]
2023-11-04 12:02:01,505 INFO: Microblog startup [in /home/kourosh/PycharmProjects/mymicroblog/app/__init__.py:88]
2023-11-04 12:02:02,232 INFO: Microblog startup [in /home/kourosh/PycharmProjects/mymicroblog/app/__init__.py:88]
2023-11-04 12:02:03,342 ERROR: Unhandled exception [in /home/kourosh/PycharmProjects/mymicroblog/./app/tasks.py:50]
Traceback (most recent call last):
  File "/home/kourosh/PycharmProjects/mymicroblog/./app/tasks.py", line 40, in export_posts
    send_email('[Microblog] Your blog posts',
  File "/home/kourosh/PycharmProjects/mymicroblog/./app/email.py", line 21, in send_email
    pass
  File "/home/kourosh/PycharmProjects/mymicroblog/venv/lib/python3.10/site-packages/flask_mail.py", line 491, in send
    with self.connect() as connection:
  File "/home/kourosh/PycharmProjects/mymicroblog/venv/lib/python3.10/site-packages/flask_mail.py", line 144, in __enter__
    self.host = self.configure_host()
  File "/home/kourosh/PycharmProjects/mymicroblog/venv/lib/python3.10/site-packages/flask_mail.py", line 158, in configure_host
    host = smtplib.SMTP(self.mail.server, self.mail.port)
  File "/usr/lib/python3.10/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python3.10/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python3.10/smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable
